/* Generated By:JavaCC: Do not edit this line. Sng2svgConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Sng2svgConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TITLEBLK = 5;
  /** RegularExpression Id. */
  int ENDTITLE = 6;
  /** RegularExpression Id. */
  int TEXTBLK = 7;
  /** RegularExpression Id. */
  int ENDTEXT = 8;
  /** RegularExpression Id. */
  int BARSBLK = 9;
  /** RegularExpression Id. */
  int ENDBARSBLK = 10;
  /** RegularExpression Id. */
  int BARSDESC = 11;
  /** RegularExpression Id. */
  int ENDBARSDESC = 12;
  /** RegularExpression Id. */
  int BARLINE = 13;
  /** RegularExpression Id. */
  int OPENREPEAT = 14;
  /** RegularExpression Id. */
  int CLOSEREPEAT = 15;
  /** RegularExpression Id. */
  int OPENDOUBLEBAR = 16;
  /** RegularExpression Id. */
  int CLOSEDOUBLEBAR = 17;
  /** RegularExpression Id. */
  int CHORD = 18;
  /** RegularExpression Id. */
  int TEXT = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"<TITLE>\"",
    "\"</TITLE>\"",
    "\"<TEXT>\"",
    "\"</TEXT>\"",
    "\"<BARS>\"",
    "\"</BARS>\"",
    "\"<DESC>\"",
    "\"</DESC>\"",
    "\"|\"",
    "\"<:\"",
    "\":>\"",
    "\"<|\"",
    "\"|>\"",
    "<CHORD>",
    "<TEXT>",
  };

}
